### ISSUE TITLE
Crash when on Kid mode/Favorites only mode if some systems do not have one such entry

### ISSUE THREAD

**Issue by pjft** [zigurana/EmulationStation#30] opened 2016-09-16 22:17 UTC
At least that's what I assume is happening. Either that or the game I've selected is in an out of bounds index after the switch.
This happened when I first turned on favorites mode, as an experiment. On reboot it was fine, but it crashed the system beforehand.
After I set a favorite on each system, it no longer crashed when I switched.
Now I set it to kid mode and it crashed.

emulationstation: /home/pi/RetroPie-Setup/tmp/build/emulation-kids/es-core/src/components/IList.h:125: const UserData& IList<EntryData, UserData>::getSelected() const [with EntryData = TextListData; UserData = FileData*]: Assertion 'size() > 0' failed. 
Aborted.

RetroPie 4.0.2.

**Comment by pjft** [comment] 2016-09-16 22:19
Actually, this seems to happen only when I am, in addition, in a platform's game list. If I am on the system select screen, it seems to work well.

**Comment by zigurana** [comment] 2016-09-16 22:42
Hey, Thanks for trying to track down this behavior, I've seen this as well,
and of course it is a genuine bug.
Apparently the redesign did not turn out all that well.
Apologies, I will need some more time to have a look at this.

Op za 17 sep. 2016 00:19 schreef pjft notifications@github.com:

**Comment by pjft** [comment] 2016-09-16 22:52
Hi!
By all means, no worries. I know these things take time. Just wanted to flag this in case you weren't aware of it :)
Unsure why I had closed the issue. I'll reopen now.
Thanks!

**Comment by VFansss** [comment] 2016-12-08 14:25
I've encountered this bug 10 seconds after end of the compiling. Crash at every reboot.

It's very sad, cause without this would be almost perfect for my setup. There's a way to fix it?

**Comment by pjft** [comment] 2016-12-08 14:32
Is it the same, though?

In my case, if you do have at least one favorite item [in the entire set of gamelists/in all platforms you have], it should work well - I don't remember which, though.

Alternatively, just go to the emulation station settings and set it to the default mode (i.e. not kids/favorites one) and it should go back to working. Then you can set your favorites correctly.

Best.

**Comment by VFansss** [comment] 2016-12-08 14:47
Yup, it's the same problem. It can be solved also SSH'ing into Rasp and edit /opt/retropie/configs/all/emulationstation/es_settings.cfg and setting <bool name="FavoritesOnly" value="false" />

If "Favourite List Only" it's enabled and even one of the game list platform is empty...ES don't work anymore.

Is very gamebreaking, at least for me. It's sad cause I'm interested only in favourite list, and I don't want to use Recalbox (that have a very advanced one).

:(

**Comment by pjft** [comment] 2016-12-08 14:51
As I said, it should work if you actually have a favorites list set. Do you have any games marked as favorites? 

This only happens if there are no games marked as favorite.

**Comment by VFansss** [comment] 2016-12-08 15:02
The problem is that if I delete every game from favourite list set...ES crash and don't work anymore, even after restarting.
Maybe isn't a killing things, but if this happen (It's a gift) I don't have any way to restore the situation, aside SSH'ing into the Pi. Isn't a very elegant way.

Cause I've a very long game list I wanted a Favourite list so much that is basically the only reason I've installed this ES branch.

This and "option menu closing lag" it's the only things that are mayor turn down on a great work like this...

**Comment by pjft** [comment] 2016-12-08 15:04
Yes, it's a known issue. 

Try not to delete every game from the favorite list for the time being. You may choose to prevent ES from saving metadata on exit, maybe that won't save the changes to the favorites list?

**Comment by VFansss** [comment] 2016-12-08 15:23
I think that changes to favourites list are done everytime "add/remove to favourite" button are pressed, cause (if there's only one game on fav list) I can destroy ES simply pressing Y (add to fav button).

So I don't think this solution would work...

**Comment by zigurana** [comment] 2016-12-08 19:55
Hey, sorry to keep this issue open for so long.
I was working on a cleaner re-implementation of this, but got bogged down
in debugging.
I got very frustrated with it all for a while, and decided to let this lie
for a while.
Currently, I am working on theming the system carousel on the main screen.
Once that is in reasonable shape, I will start working on this again.

For now, do not remove all favorites while in favorites only mode.
Alternatively, have a look at the code and suggest a solution, I'm open to
suggestions (really!).

Op do 8 dec. 2016 16:23 schreef Alessio Di Giacomo <notifications@github.com

**Closed as completed** 2017-05-08 19:00 UTC
Labels: bug
